// Generated by CoffeeScript 1.3.3
(function() {
  var Analyzer;

  Analyzer = (function() {

    function Analyzer(dictionary_path) {
      var caller;
      this.ready = false;
      this.afinn = {};
      caller = this;
      $.get(dictionary_path, function(data) {
        var line, lines, value, word, _i, _len, _ref;
        lines = data.split('\n');
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line = lines[_i];
          _ref = line.split('\t'), word = _ref[0], value = _ref[1];
          caller.afinn[word] = parseInt(value);
        }
        return caller.ready = true;
      });
    }

    Analyzer.prototype.analyze = function(text) {
      var sentiments, sqrt, sum, word, words, _i, _len;
      words = text.toLowerCase().split(/\W+/);
      sentiments = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (this.afinn[word] !== void 0) {
          sentiments.push(this.afinn[word]);
        }
      }
      sum = sentiments.reduce(function(t, s) {
        return t + s;
      });
      sqrt = Math.sqrt(sentiments.length);
      console.log(sum, sqrt, sum / sqrt);
      return sum / sqrt;
    };

    return Analyzer;

  })();

  this.analyzer;

  this.analyzer = new Analyzer('AFINN-111-emo.txt');

  analyzer.analyze("The cool thing about Hulu Plus is that I pay for it but also get ads and I can't watch Wilfred on my iPad hey wait that's not so cool.");

}).call(this);
