// Generated by CoffeeScript 1.3.3
(function() {
  var Analyzer;

  Analyzer = (function() {

    function Analyzer(dictionary_path) {
      var caller;
      this.afinn = {};
      this.queue = [];
      this.running = false;
      this.ready = false;
      caller = this;
      $.get(dictionary_path, function(data) {
        var line, lines, value, word, _i, _len, _ref;
        lines = data.split('\n');
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line = lines[_i];
          _ref = line.split('\t'), word = _ref[0], value = _ref[1];
          caller.afinn[word] = parseInt(value);
        }
        caller.ready = true;
        return caller.work();
      });
    }

    Analyzer.prototype.analyze = function(text, callback) {
      var sentiments, sqrt, sum, word, words, _i, _len;
      words = text.toLowerCase().split(/\W+/);
      sentiments = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (this.afinn[word] !== void 0) {
          sentiments.push(this.afinn[word]);
        }
      }
      sum = sentiments.reduce(function(t, s) {
        return t + s;
      });
      sqrt = Math.sqrt(sentiments.length);
      return callback(text, sum / sqrt);
    };

    Analyzer.prototype.addToQueue = function(text, callback) {
      this.queue.push({
        'text': text,
        'callback': callback
      });
      if (!this.running && this.ready) {
        return work();
      }
    };

    Analyzer.prototype.work = function() {
      var job;
      this.running = true;
      while (this.queue.length > 0) {
        job = this.queue.shift();
        this.analyze(job.text, job.callback);
      }
      return this.running = false;
    };

    return Analyzer;

  })();

  this.analyzer;

  this.analyzer = new Analyzer('AFINN-111-emo.txt');

  analyzer.addToQueue("The cool thing about Hulu Plus is that I pay for it but also get ads and I can't watch Wilfred on my iPad hey wait that's not so cool.", function(text, sentiment) {
    return console.log(text, sentiment);
  });

  analyzer.addToQueue("Could @hulu please remind me what my #HuluPlus subscription is for?!?!? Why do I pay $$ for ads and can't watch messages?!?!?", function(text, sentiment) {
    return console.log(text, sentiment);
  });

}).call(this);
